[package]
name = "ostrich"
version = "0.1.0"
edition = "2021"

[lib]
name = "ostrich"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.2"
numpy = "0.21"

[profile.release]
strip = "debuginfo"
# lto = true
# codegen-units = 1
